// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVxHYw1qJb0nfaQXeJcxt7QtLE5D29-5Q',
    appId: '1:329266640062:web:cd08e6d7018b5cc3fedaef',
    messagingSenderId: '329266640062',
    projectId: 'chanzo-d14ef',
    authDomain: 'chanzo-d14ef.firebaseapp.com',
    storageBucket: 'chanzo-d14ef.firebasestorage.app',
    measurementId: 'G-4M7YPRSG6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUD-lJvOodE7B7cftrQJMGy-9i9nmPntQ',
    appId: '1:329266640062:android:f7f70aaea656d137fedaef',
    messagingSenderId: '329266640062',
    projectId: 'chanzo-d14ef',
    storageBucket: 'chanzo-d14ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd7wHhGT8BxP_gJKA3f8Xy9v-VhKpMFW4',
    appId: '1:329266640062:ios:b6079108a3937e36fedaef',
    messagingSenderId: '329266640062',
    projectId: 'chanzo-d14ef',
    storageBucket: 'chanzo-d14ef.firebasestorage.app',
    iosBundleId: 'com.chanzo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd7wHhGT8BxP_gJKA3f8Xy9v-VhKpMFW4',
    appId: '1:329266640062:ios:b6079108a3937e36fedaef',
    messagingSenderId: '329266640062',
    projectId: 'chanzo-d14ef',
    storageBucket: 'chanzo-d14ef.firebasestorage.app',
    iosBundleId: 'com.chanzo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVxHYw1qJb0nfaQXeJcxt7QtLE5D29-5Q',
    appId: '1:329266640062:web:4587cb94b0892f45fedaef',
    messagingSenderId: '329266640062',
    projectId: 'chanzo-d14ef',
    authDomain: 'chanzo-d14ef.firebaseapp.com',
    storageBucket: 'chanzo-d14ef.firebasestorage.app',
    measurementId: 'G-7R42KTPK8T',
  );
}
